### ISSUE TITLE
Single quote check is missed in presence of ${{ }} in if

### ISSUE THREAD

**Issue by varungandhi-src** [rhysd/actionlint#110]
Minimal example:

```yaml
name: test
on:
  push:
jobs:
  x:
    runs-on: ubuntu-latest
    if: ${{ github.repository }} == "a/a"
    steps:
    - name: a
      run: echo "a"
```

This doesn't [emit any errors](https://rhysd.github.io/actionlint/#eJwljcEKwyAQRO9+xSC52t6FfIwWWy3NKu4utIT8e6K9DAzzZobCljwksZhK3gBNOXtj3jXysN8hQFdidwHQqCTqPmFWRlSeHsu+41Uka7z11CoXqf2H48C6woZ7sJNkSY3/ew40j8N0c98jPXK9cHsCCkErNg==).

However, there is an error about double quotes if you replace `${{ github.repository }}` with `github.repository`, which seems like the right behavior based on https://github.com/actions/runner/issues/866. Would it make sense to emit the same error when `${{ github.repository }}` is used?
