### ISSUE TITLE
Provide a GitHub action on actionlint

### ISSUE THREAD

**Issue by toast-gear** [rhysd/actionlint#117]
👋 

I know you document how to use actionlint in a pipeline, it's also handy being able to run it locally.

We use actionlint in our pipelines though and actionlint not being a proper action means keeping on top of bumping it is hacky with something custom or we just pull down latest. If there was a proper action for this then dependabot could be used to bump the action automating the process with a known off the shelf tool. If you don't want to spend the time mkaing this repository work as an action too like https://github.com/mikefarah/yq then you could just produce a wrapper repository like https://github.com/bridgecrewio/checkov-action and just automate bumping the underlying container.

**Comment by Ameausoone** [comment]
I'm using https://github.com/reviewdog/action-actionlint which do the job.

**Comment by toast-gear** [comment]
Neat I didin't know that existed! Certainly helpful and perhaps @rhysd could take inspiration from it and produce a "official" action for actionlint 😅😄

**Comment by Ameausoone** [comment]
There is already a lot of users : 

![image](https://user-images.githubusercontent.com/592978/168995606-dd443bc8-28a8-47d9-a308-0c96191f6c3c.png)

But it would be interesting to integrate [reviewdog/action-actionlint](https://github.com/reviewdog/action-actionlint) in this repo. And in addition, if you would add an automatic semantic release action, cli and github action would be released as soon as you merge on main (cf https://github.com/marketplace/actions/release-that , https://goreleaser.com/cookbooks/semantic-release/) 👌

**Comment by rhysd** [comment]
Hmm, honestly I don't think dedicated action only for setup for actionlint since we already have the download script.

https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions

However, this issue gained some upvotes and I understood actually some users want an action. I will consider it.

> But it would be interesting to integrate [reviewdog/action-actionlint](https://github.com/reviewdog/action-actionlint) in this repo.

Putting an action in rhysd/actionlint repository is not possible because currently this repository is already using Git tags for releases. But an action also requires Git tags for releases. So they will have conflicts. I think separate repository is necessary.

**Comment by ericcornelissen** [comment]
> Hmm, honestly I don't think dedicated action only for setup for actionlint since we already have the download script.
> 
> [main/docs/usage.md#use-actionlint-on-github-actions](https://github.com/rhysd/actionlint/blob/main/docs/usage.md?rgh-link-date=2022-05-20T12%3A18%3A09Z#use-actionlint-on-github-actions)
> 
> However, this issue gained some upvotes and I understood actually some users want an action. I will consider it.
>
> [...]
>
> > If there was a proper action for this then GitHub native tools like dependabot could be used to bump the action automating the process with a known off the shelf tool whilst retaining the determinism of version pinning.
>
> [...]

Chiming in here related to this point: per my understanding of the install script it will always download the latest version of actionlint. This can be undesirable as this means builds are not reproducible. The most notable way in which this manifest itself is that the job using actionlint might start failing without having changed any workflows.

Admittedly, this reproducibility problem can be avoided by using the Docker image or using `go install` (if `go` is set up for the job). However, as far as I know, neither of these approaches has support for version updates by tools like Dependabot.

For these reasons, I believe having a "proper GitHub action" would be preferable - I believe this is also what the original issue author was getting at, specifically:

> Does this mean the action provides a feature like below?
> 
> - Check all `uses:` in steps of given workflows
> - When a version of action in `uses:`, actionlint raises an error
> - The action generates a PR to bump the versions

No, these things would all be carried out by Dependabot (or similar).

**Comment by ES-Alexander** [comment]
Supply chain attacks are a growing concern for many projects, so blindly using the latest version of the download script to attempt to download any version of actionlint (latest or specific) seems ill-advised (and the same applies for using some random developer's Action wrapper). It is of course possible to [_also_ tie down the script download URL to a specific commit hash](https://github.com/ArduPilot/ardupilot/pull/33213), but that still feels like some awkward redirection that's extra work to manage, and could be avoided with a dedicated Action.

#262 was an approach for this, but didn't get followed through because of a conflict with how the repo's tags get managed. I don't imagine most users care about exactly _how_ an Action gets created/released (e.g. in this repo or a separate one), but having an _official_ Action would help to use this project with more confidence. As a beneficial side-effect, the Action to run actionlint could also be used to configure it, which would avoid needing a separate config file.

> Users of GitHub Actions usually specify only major version ...

How and when users choose to update is up to them. The request here is to provide more convenient control over how actionlint can be integrated, in a way that maintains user reliance on only/primarily this project (e.g. they do not need to trust a middleman for a convenience feature).

I understand making and maintaining a GitHub Action is additional work - hopefully this comment helps explain why people would value such a feature :-)

**Comment by ryandens** [comment]
For folks who are interested in pinning both actionlint itself + the script used to download it, while still having renovate automatically manage upgrades, I did the following

Relatively simple action: 

```yaml
  # Lints the GitHub Actions workflow files themselves.
  # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # The actionlint version and the download script's pinned commit are kept
      # in lockstep with upstream GitHub release tags by Renovate — the commit
      # below is the v1.7.11 tag. See the customManager in renovate.json.
      - name: Download actionlint
        id: get_actionlint
        env:
          ACTIONLINT_VERSION: 1.7.12
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/914e7df21a07ef503a81201c76d2b11c789d3fca/scripts/download-actionlint.bash) "$ACTIONLINT_VERSION"
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
```


`renovate.json` with custom manager: 

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended"
  ],
  "minimumReleaseAge": "1 day",
  "internalChecksFilter": "strict",
  "customManagers": [
    {
      "customType": "regex",
      "description": "Keep actionlint's version and its pinned download-script commit in lockstep with upstream GitHub release tags",
      "managerFilePatterns": [
        "/^\\.github/workflows/.+\\.ya?ml$/"
      ],
      "matchStrings": [
        "ACTIONLINT_VERSION:\\s*(?<currentValue>\\S+)[\\s\\S]*?raw\\.githubusercontent\\.com/rhysd/actionlint/(?<currentDigest>[0-9a-f]{40})/"
      ],
      "depNameTemplate": "rhysd/actionlint",
      "datasourceTemplate": "github-tags",
      "extractVersionTemplate": "^v?(?<version>.+)$"
    }
  ]
}
```
