### ISSUE TITLE
False positives in reusable workflows for org level secrets

### ISSUE THREAD

**Issue by bewuethr** [rhysd/actionlint#141]
I have a workflow that calls a reusable workflow and passes a secret:

```yaml
name: Caller workflow

on:
  workflow_dispatch:

jobs:
  call:
    name: Call reusable workflow
    uses: myorg/actions/.github/workflows/reusable.yml@main
    secrets:
      token: ${{ secrets.SPECIAL_TOKEN }}
```

In the reusable workflow, I refer to that secret, but I also use an org-level secret:

```yaml
name: Reusable workflow

on:
  workflow_call:
    secrets:
      token:
        description: A secret token
        required: true

jobs:
  something:
    name: Do something with secrets
    runs-on: ubuntu-20.04

    steps:
      - name: Print secrets
        run: |
          echo "${{ secrets.token }}"
          echo "${{ secrets.ORG_LEVEL_SECRET }}"
```

This job runs fine. However, actionlint complains:

```txt
reusable.yml:17:52: property "org_level_secret" is not defined in object type {actions_runner_debug: string; token: string; github_token: string; actions_step_debug: string} [expression]
```

I believe this is a false positive. The check seems to be described [here](https://github.com/rhysd/actionlint/blob/main/docs/checks.md#check-types-of-inputs-and-secrets-in-reusable-workflow). The assumption that every reference to the `secret` object must be declared in `on.workflow_call.secrets` doesn't hold in this case.

**Comment by rhysd** [comment]
@bewuethr That's because you didn't declare the `ORG_LEVEL_SECRET` secret. Is it set by GitHub Actions runtime? If so, please provide the document of the secret. Otherwise, you need to declare it:

```yaml
on:
  workflow_call:
    secrets:
      token:
        description: A secret token
        required: true
      org_level_secret:
        description: ...

**Comment by rhysd** [comment]
OK, I understood your point. The secret is set in org-level. So it is available in workflows of the org even if it is not declared. Am I correct?

Hmm, this is difficult for actionlint because actionlint does not know what secrets are set in org-level.

**Comment by bewuethr** [comment]
> OK, I understood your point. The secret is set in org-level. So it is available in workflows across the org even if it is not declared. Am I correct?
> 
> Hmm, this is difficult for actionlint because actionlint does not know what secrets are set in org-level.

Yes, this is exactly right. It's a secret available to every repository in the organization. I can just pass such a secret to the reusable workflow, but I'd like not to because that keeps the call site simpler (my actual workflow uses half a dozen such secrets).

Maybe something like a default setting for a secret?

```yaml
on:
  workflow_call:
    secrets:
      org_level_secret:
        description: An org level secret
        required: false
        default: ${{ secrets.ORG_LEVEL_SECRET }}
```

so at least within the workflow you'd only reference known secrets?
