### ISSUE TITLE
Type-check boolean expression coercion

### ISSUE THREAD

**Issue by rethab** [rhysd/actionlint#147]
Consider the below workflow, which has two problems. I have ran this through the [actionlint playground](https://rhysd.github.io/actionlint/#eJxtUDFywzAM2/0KxEM82Q/QXcYMfUVPtulaiSq6InW5/L6S3DodupEgCYDgYBrgwfG+eH68T9b7AgAubEllrwEKdvQ0/7bATItNXg00JvqDyhTdpo6DQXutR+CI2UktdaVDqz2uIn0lFzM7FuvlxabPjQxGZk82NM2Nx+rnIxLp7iSmIH3RSmMKmnpvlUTrSJS2w35fNg1oWhmdMULac9L8IIL9pIsdJ2OqdneIu2xH7m77h+ENsnLyc4Fe+0v+eA9t+EkLpwu6kk+H8xmn6mgonMMuLkNOsf0GnstzZQ==) but no problems were found.

```yaml
on:
  workflow_call:
    inputs:
      enabled:
        default: true
        description: "Enable or disable the workflow"
        required: false
        type: boolean

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::set-output name=abc::false'
        id: skip
      - run: echo I should run
        if: "inputs.enabled != 'true' && !steps.skip.outputs.def"
```

- Problem 1: **Inputs are actual booleans**, but the expression compares `enabled` to `'true'` which is a string. This will never be true
- Problem 2: **Outputs are always strings**, but the expression uses a the boolean not operator `!` which means `'false'` is treated as a truthy value and therefore `!('false')` is actually `false`

GitHub Docs on Expressions: https://docs.github.com/en/actions/learn-github-actions/expressions#operators

Could actionlint be extended to catch these cases as well?
