### ISSUE TITLE
Mix inherited with declared secrets

### ISSUE THREAD

**Issue by rethab** [rhysd/actionlint#148]
actionlint assumes that in reusable workflows, you're either inheriting secrets or declare them.

It is possible to mix them though. Consider this:

```
on:
  workflow_call:
    secrets:
      repositoryUrl:
        required: false

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      uses: abc/upload@v1
      with:
        url: ${{ secrets.repositoryUrl || secrets.GLOBAL_REPOSITORY_URL }}
```

This reusable workflow can be called either with `secrets: inherit` or by passing the `repositoryUrl` secret explicitly.

Any chance to support this?
