### ISSUE TITLE
`inputs` context not supported for `workflow_dispatch`

### ISSUE THREAD

**Issue by joshbolduc** [rhysd/actionlint#152]
Thanks for providing this helpful tool!

GitHub [recently added support for referencing the `inputs` context with `workflow_dispatch`](https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/), in addition to `github.event.inputs`. The [docs now present `inputs` as the primary way to retrieve input passed to `workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs) with this note:

> **Note:** The workflow will also receive the inputs in the `github.event.inputs` context. The information in the `inputs` context and `github.event.inputs` context is identical except that the `inputs` context preserves Boolean values as Booleans instead of converting them to strings.

So a workflow file like the following:
```yml
name: Example

on:
  workflow_dispatch:
    inputs:
      my_input:
        type: string
        required: true

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.inputs.my_input }}
        run: echo test
      - if: ${{ inputs.my_input }}
        run: echo test
```

should work, but actionlint reports this error:
```
example.yml:16:17: property "my_input" is not defined in object type {} [expression]
   |
16 |       - if: ${{ inputs.my_input }}
   |    
```
