### ISSUE TITLE
Shellcheck errors when running from actionlint Docker container

### ISSUE THREAD

**Issue by politician** [rhysd/actionlint#153]
Worfklow file:

```yaml
name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: "echo test"
```yaml

If I run actionlint directly, **no problem**. However, if I run via Docker:

```sh
docker run -v $PWD:/project --workdir /project rhysd/actionlint:latest -verbose
```

Then I get the following:

```txt
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
verbose: Linting all workflow files in repository: .
verbose: Detected project: /project
verbose: Collected 8 YAML files
verbose: Linting 8 files
verbose: verbose: Linting .github/workflows/lint.yaml
verbose: Linting .github/workflows/issue-voting.yaml
verbose: verbose: Using project at /project
verbose: Linting .github/workflows/stale.yaml
verbose: Using project at /project
verbose: verbose: Linting .github/workflows/pr-helper.yaml
verbose: Using project at /project
Linting .github/workflows/leaked-secrets.yaml
verbose: Using project at /project
verbose: Using project at /project
Linting .github/workflows/test-dev-workflow.yaml
verbose: Using project at /project
verbose: Linting .github/workflows/deploy-docs.yaml
verbose: Using project at /project
Linting .github/workflows/rebase.yaml
verbose: Using project at /project
verbose: verbose: verbose: verbose: verbose: verbose: Found 0 parse errors in 45 ms for .github/workflows/deploy-docs.yaml
verbose: Found 0 parse errors in 45 ms for .github/workflows/rebase.yaml
Found 0 parse errors in 44 ms for .github/workflows/leaked-secrets.yaml
Found 0 parse errors in 45 ms for .github/workflows/lint.yaml
verbose: Found 0 parse errors in 45 ms for .github/workflows/test-dev-workflow.yaml
Found 0 parse errors in 45 ms for .github/workflows/stale.yaml
Found 0 parse errors in 45 ms for .github/workflows/issue-voting.yaml
Found 0 parse errors in 45 ms for .github/workflows/pr-helper.yaml
verbose: Found total 0 errors in 83 ms for .github/workflows/stale.yaml
verbose: Found total 0 errors in 83 ms for .github/workflows/issue-voting.yaml
verbose: Found total 0 errors in 83 ms for .github/workflows/leaked-secrets.yaml
verbose: Found total 0 errors in 83 ms for .github/workflows/pr-helper.yaml
verbose: Found total 0 errors in 83 ms for .github/workflows/rebase.yaml
verbose: Found total 0 errors in 83 ms for .github/workflows/lint.yaml
fatal error while checking .github/workflows/test-dev-workflow.yaml: `/usr/bin/shellcheck --norc -f json -x --shell bash -e SC1091,SC2194,SC2050,SC2154,SC2157 -` did not run successfully while checking script at line:9,col:9: /usr/bin/shellcheck was terminated. stderr: ""
```
