### ISSUE TITLE
false negative on use `env` in `env` definition

### ISSUE THREAD

**Issue by kazuk** [rhysd/actionlint#158]
this commit passes `actionlint`

https://github.com/kazuk/sbom-ghr/pull/2/commits/fe18f2d3e424548e791ab9335ea4bc63e662a4e4

but `The workflow is not valid. ` shown as bellow.

```
The workflow is not valid. .github/workflows/rust.yml (Line: 18, Col: 18): Unrecognized named-value: 'env'. Located at position 1 within expression: env.KEY_PREFIX .github/workflows/rust.yml (Line: 43, Col: 22): Unrecognized named-value: 'env'. Located at position 1 within expression: env.KEY_PREFIX
```

**Comment by rhysd** [comment]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env

> Variables in the env map cannot be defined in terms of other variables in the map.

Official document mentioned this limitation here.

https://docs.github.com/en/actions/learn-github-actions/contexts#env-context

> You can use the env context in the value of any key in a step except for the id and uses keys. 

`id` and `uses` also seem to ban `env` context.

**Comment by rhysd** [comment]
Now workflow like below

```yaml
on: push

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      FOO: aaa
    steps:
      - uses: test/${{ env.FOO }}@main
        env:
          BAR: ${{ env.FOO }}
        id: foo-${{ env.FOO }}
```

causes errors as follows:

```
test.yaml:9:24: undefined variable "env". available variables are "github", "inputs", "job", "matrix", "needs", "runner", "secrets", "steps", "strategy" [expression]
  |
9 |       - uses: test/${{ env.FOO }}@main
  |                        ^~~~~~~
test.yaml:11:20: undefined variable "env". available variables are "github", "inputs", "job", "matrix", "needs", "runner", "secrets", "steps", "strategy" [expression]
   |
11 |           BAR: ${{ env.FOO }}
   |                    ^~~~~~~
test.yaml:12:21: undefined variable "env". available variables are "github", "inputs", "job", "matrix", "needs", "runner", "secrets", "steps", "strategy" [expression]
   |
12 |         id: foo-${{ env.FOO }}
   |                     ^~~~~~~
```
