### ISSUE TITLE
Description key is not required for workflow_call secrets

### ISSUE THREAD

**Issue by roryabraham** [rhysd/actionlint#174]
The following syntax:

```yaml
name: Callable Workflow

on:
  workflow_call:
    secrets:
      MY_TOKEN:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment --body "Test comment"
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
```

Results in an error:

`"description" is missing at "my_token" secret of workflow_call event`

However, the description is optional.
