### ISSUE TITLE
inputs context not supported for workflow_call?

### ISSUE THREAD

**Issue by oshaughnessy** [rhysd/actionlint#176]
I see the same symptoms as described in #152 when referencing inputs from a `workflow_call` definition. E.g. from this simplified workflow:

```
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Prefix for name of built asset zip file"
        default: build-server
        required: false
        type: string
      build-env:
        description: "Build Environment (dev, test, qa, staging, prod)"
        default: dev
        required: false
        type: string

...

jobs:
  build:
    name: build-${{ matrix.targetPlatform }}
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.build-env }}-${{ matrix.targetPlatform }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.aws-region }}
          role-duration-seconds: 14400
          role-session-name: build-${{ matrix.targetPlatform }}-${{ inputs.build-env }}
          role-to-assume: ${{ secrets.aws-role-to-assume }}
```

Output from `actionlint`:

```
workflow.yml:X:41: property "build-env" is not defined in object type {} [expression]
    |
X |       group: ${{ github.workflow }}-${{ inputs.build-env }}-${{ matrix.targetPlatform }}-${{ github.ref }}

workflow.yml:Y:82: property "build-env" is not defined in object type {} [expression]
    |
Y |           role-session-name: build-${{ matrix.targetPlatform }}-${{ inputs.build-env }}
```

Is it possibly a similar issue? The workflows do work.

Thank you.

**Comment by cathex-matt** [comment]
Hi,

I got a similar issue from a workflow_call triggered workflow which works fine:

```yaml
actionlint 1.6.8 is already installed
.github/workflows/notifier.yml:119:30: property "slack_alerts_webhook" is not defined in object type {} [expression]
    |
119 |           SLACK_WEBHOOK: ${{ secrets.SLACK_ALERTS_WEBHOOK }}
```

**Comment by rhysd** [comment]
@oshaughnessy @cathex-matt 

Can you provide an entire workflow file so that I can reproduce the same issue on my side.

**Comment by rhysd** [comment]
I tried the following input but this issue did not happen:

```yaml
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Prefix for name of built asset zip file"
        default: build-server
        required: false
        type: string
      build-env:
        description: "Build Environment (dev, test, qa, staging, prod)"
        default: dev
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.aws-region }}
          role-duration-seconds: 14400
          role-session-name: build-xxxx-${{ inputs.build-env }}
          role-to-assume: ${{ secrets.aws-role-to-assume }}
```
