### ISSUE TITLE
"is not defined in object type" error with marketplace action

### ISSUE THREAD

**Issue by frank-long** [rhysd/actionlint#18]
I'm using dorny/paths-filter and that sets a dynamic output for me, but actionlint is complaining about the output not being there, see code below. I can't see how I can fix that.

```
- name: Checkout repo
        uses: actions/checkout@v2
      - id: filterchanges
        uses: dorny/paths-filter@v2
        with:
          filters: 'files: .github/workflows/*.yml'
      - name: lint
        if: ${{ steps.filterchanges.outputs.files == 'true'}}
[actionlint] reported by reviewdog 🐶 property "files" is not defined in object type {changes: any} [expression]


```
