### ISSUE TITLE
Serializing workflow AST to JSON

### ISSUE THREAD

**Issue by behnazh-w** [rhysd/actionlint#191]
I'm trying to serialize the workflow AST generated by `actionlint` to JSON using the code below:
```go
workflow, parse_err := actionlint.Parse(data)
result, json_err := json.Marshal(workflow)
```

Which works fine in most cases except for the following example for which I get `json: unsupported type: map[*actionlint.String]*actionlint.WorkflowCallEventInput`:
```yaml
name: Example
on:
  workflow_call:
    outputs:
      foo:
        description: Foo
        value: ${{ jobs.example.outputs.foo }}

jobs:
  example:
    outputs:
      foo: ${{ steps.example.outputs.foo }}
    name: Example 
    runs-on: ubuntu-latest
    steps:
    - name: example
      id: example
      shell: bash
      run: |
        echo "::set-output name=foo::bar"
```

Do you have any plans to make the workflow AST serializable? If not, could you please provide guidance on creating a PR?
