### ISSUE TITLE
Validate `workflow_run` values

### ISSUE THREAD

**Issue by GustavoKatel** [rhysd/actionlint#204]
Is it possible to validate whether the workflow name defined in a `workflow_run` exists or not?

Something like:

```yaml
on:
  workflow_run:
    workflows: [Run Tests] # <- This would raise an error if "Run Tests" does not exist in the workflow files.
    types:
      - completed
```

It doesn't seem to be validating that right now.

Docs for `workflow_run`: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
