### ISSUE TITLE
Allow inputs context in workflow_dispatch checks.

### ISSUE THREAD

**Issue by jgreat** [rhysd/actionlint#210]
Looks like GHA `workflow_dispatch` now allows using the `inputs` context in addition to digging the inputs out of `github.events.inputs`. Seems that actionlint doesn't know about this change yet. 

https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs

Example error
```
.github/workflows/delete.yaml:24:22: property "namespace" is not defined in object type {} [expression]
   |
20 |       namespace: ${{ inputs.namespace }}
   |                      ^~~~~~~~~~~~~~~~
```

Example workflow

```yaml
name: delete

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Target Namespace"
        type: string
        required: true
      delete_namespace:
        description: "Delete Target Namespace"
        type: boolean
        required: true
        default: true

jobs:
  reset:
    uses: ./.github/workflows/workflow-dev-reset.yaml
    with:
      namespace: ${{ inputs.namespace }}
      delete_namespace: ${{ inputs.delete_namespace }}
```
