### ISSUE TITLE
Extend security checks with workflow_dispatch event untrusted inputs 

### ISSUE THREAD

**Issue by skhomuti** [rhysd/actionlint#213]
Hey! actionlint is awesome tool!

We already have injections checks from #19, it is really untrusted user input from users not having any rights on the repository. 
I would like to extend these checks with inputs from the common developers (who doesn't have admin rights and access to the repo secrets). For example `inputs` from `workflow_dispatch` event:
```
on:
  workflow_dispatch:
    inputs:
      str:
        required: false
        type: string
        description: echo${IFS}hello;env

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.str }}
      - run: echo ${{ github.event.inputs.str }}

      - name: escape untrusted input
        env:
          STR: ${{ github.event.inputs.str }}
        run: echo $STR
```

Would great know your opinion for this feature :)
