### ISSUE TITLE
Alert when newer version of action is available

### ISSUE THREAD

**Issue by andreasabel** [rhysd/actionlint#228]
It would be great if `actionlint` alerted me when a newer version of an action is available.  E.g. for `uses: actions/cache@v2` it would alert me that `v3` is the latest version.  Actionlint could end its report with a list of outdated actions and their latest versions.

**Comment by Ameausoone** [comment]
Dependabot already does the job, see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Just add this in `dependabot.yml` :

```yaml
# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
```
