### ISSUE TITLE
Support for configuration variables in workflows (`vars`)

### ISSUE THREAD

**Issue by s-t-hg** [rhysd/actionlint#259]
It seems that the newly implemented `vars` need to be supported.
https://github.blog/changelog/2023-01-10-github-actions-support-for-configuration-variables-in-workflows/

For example:

```yml
on:
  push:
jobs:
  display-variables:
    runs-on: ${{ vars.RUNNER }}
    steps:
    - name: Use variables
      run: |
        echo "Repository variable : ${{ vars.REPOSITORY_VAR }}"
        echo "Organization variable : ${{ vars.ORGANIZATION_VAR }}"
```

https://rhysd.github.io/actionlint/#eJxtjUEOgjAQRfecYmLc4gG6Y0EMm9ZUMNGNKdpIDXaaDpggcnelQWKMyz/vz/toWQTgWqpYdMWSxnQ25GrVxXfljSprHY4AvrUUo2Ww7Ht4M1rJgvNUwjAETo12UzUGq26aQUEaZksgQcPgOQUAfaoQFlI7JNOg7+Y+fA+lG7HNciH3x10yDi5+/oW/KGseqjFo/xqEXCc8OyR5JvjH8QLJF00M

![image](https://user-images.githubusercontent.com/108658936/212584650-61b3c0ab-762e-4f06-b985-8f725a2571f4.png)
