### ISSUE TITLE
Actionlint does not report expressions that reference github "Default environment variables" via f.x `${{ env.CI }}`

### ISSUE THREAD

**Issue by georgespalding** [rhysd/actionlint#264]
I'm still learning the nitty gritty details of github pipelines and made a mistake, which I expected `actionlint` to report.

The following job uses an invalid expression which if I understand the docs can never have a value (but I falsely assumed default env vars could be referenced this way):

```yaml
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> ${{ env.GITHUB_OUTPUT }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}}
```

The linter gladly accepted this, but pipelines reported an error like:

```text
Run run: echo "test=hello" >> 
/home/runner/work/_temp/bc198ppp-5969-4beb-9aca-fa92b5578c95.sh: line 1: syntax error near unexpected token `newline'
Error: Process completed with exit code 2.
```

Reading about [Naming conventions for environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#naming-conventions-for-environment-variables),
I don't think that any [Default environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) are valid when referenced like this: `${{ env.GITHUB_WORKSPACE }}`.

Being new to `actionlint`, and still learning github pipelines, it would have been very helpful to have `actionlint` report that this was an invalid expression.

Would it be possible to extend `actionlint` to check for expressions referencing default variables this way?
