### ISSUE TITLE
undefined variable "context" with actions/github-script

### ISSUE THREAD

**Issue by artis3n** [rhysd/actionlint#278]
<https://github.com/actions/github-script> adds variables available to the `script` input parameter of the action:
![image](https://user-images.githubusercontent.com/6969296/219776667-53a78370-1f78-4a0d-94ad-c8aacb110f89.png)

Following the [examples](https://github.com/actions/github-script#examples) on `actions/github-script`, I'm referencing the repo owner and name with `context.repo.owner`/`context.repo.repo`. actionlint doesn't like that:

```
.github/workflows/apply.yaml:57:120: undefined variable "context". available variables are "env", "github", "inputs", "job", "matrix", "needs", "runner", "secrets", "steps", "strategy", "vars" [expression]
```

My step looks like this:

```yaml
- name: Merge PR
  uses: actions/github-script@v6
  if: ${{ github.event_name == 'pull_request_review' }}
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      github.rest.pulls.merge({
        owner: context.repo.owner,
        repo: context.repo.repo,
        pull_number: ${{ context.payload.pull_request.number }}
      })
```

Given `actions/github-script` is owned by GitHub, it'd be nice if actionlint can recognize acceptable top-level variables for that action by default. Otherwise, it'd be great if we could customize the `actionlint.yaml` to recognize these top-level variables, similar to `self-hosted-runner` (although that introduces the possibility that we reference it inappropriately in another step and actionlint doesn't flag it).
