### ISSUE TITLE
Allow for different GHES versions

### ISSUE THREAD

**Issue by killermoehre** [rhysd/actionlint#286]
Hi,

at $company, we have a GHES 3.6, which uses different workflow commands and such.

Would be lovely to be able to configure the syntax version to check in `actionlint`.

BR
Silvio

**Comment by killermoehre** [comment]
So, I bisected the tags and found that `1.6.21` is the version matching with GHES 3.6.

So, for `.pre-commit-config.yaml`, one can use

```yaml
repos:
  - repo: local
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        entry: actionlint
        language: golang
        additional_dependencies:
          - "github.com/rhysd/actionlint/cmd/actionlint@v1.6.21"  # last version compatible with GHES3.6
        types:
          - yaml
        files: "^.github/workflows/"
```

Still, would be nice if this could be configured in the `actionlint.yaml`.
