### ISSUE TITLE
actionlint internal filter cant find the correct uses

### ISSUE THREAD

**Issue by prisis** [rhysd/actionlint#304]
It looks like the current filter implemantation cant find the correct skip, if the action use a hash as a number

Example:

Works:

```
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: ...
      - run: npm run lint:md
        if: ${{ steps.filter.outputs.md == 'true' }}
```

Does not work

```
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: "dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50"  # v2.11.1
        id: filter
        with:
          filters: ...
      - run: npm run lint:md
        if: ${{ steps.filter.outputs.md == 'true' }}
```

After the switch to the hash, im currently hitting #18  again
