### ISSUE TITLE
Case sensitivity?

### ISSUE THREAD

**Issue by eitsupi** [rhysd/actionlint#31]
Thank you for the excellent service.

When I ran the following workflow check on the web, I got an error that I think was caused by uppercase letters being identified as lowercase.
https://rhysd.github.io/actionlint/

```yml
name: Create new release
on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
```

![image](https://user-images.githubusercontent.com/50911393/129475627-43662df7-bbab-4bdd-bed0-be3094c6664f.png)
