### ISSUE TITLE
Disable shellcheck when shell is powershell or pwsh

### ISSUE THREAD

**Issue by lorengordon** [rhysd/actionlint#315]
I'm trying to figure out how to disable the shellcheck integration only when the shell is powershell or pwsh. I know about `-shellcheck=`, but for projects that exercise both linux and windows runners, we _want_ shellcheck to run on the linux runners. Is there any way to exempt some workflow files from shellcheck entirely?

Here's a run with an example of the failure we're seeing: https://github.com/plus3it/actions-workflows/actions/runs/5380111038/jobs/9762319339?pr=18

**Comment by rhysd** [comment]
Please pass empty value to `-shellcheck` option then shellcheck is disabled.

```sh
actionlint -shellcheck=
```

**Comment by rhysd** [comment]
Please branch your workflow step.

```yaml
- run: actionlint
  if: ${{ runner.os != 'Windows' }}
- run: actionlint -shellcheck=
  if: ${{ runner.os == 'Windows' }}
```

It doesn't make sense to disable shellcheck on Windows because shellcheck supports Windows.
