### ISSUE TITLE
sparse-checkout argument of actions/checkout causes actionlint error

### ISSUE THREAD

**Issue by jamiekt** [rhysd/actionlint#318]
Making you aware of a possible bug.

actions/checkout recently received support for `sparse-checkout`. This was added in https://github.com/actions/checkout/pull/1317 and is documented at https://github.com/actions/checkout#fetch-only-a-single-file

I tried using it in one of my workflows like so:

```yml
            steps:
                - name: Checkout some repo
                  uses: actions/checkout@v3
                  with:
                      repository: owner/repo
                      sparse-checkout: |
                          .env
```

and actionlint threw an error:

> .github/workflows/workflow.yml:35:23: input "sparse-checkout" is not defined in action "actions/checkout@v3". available inputs are "clean", "fetch-depth", "github-server-url", "lfs", "path", "persist-credentials", "ref", "repository", "set-safe-directory", "ssh-key", "ssh-known-hosts", "ssh-strict", "submodules", "token" [action]
