### ISSUE TITLE
Incorporate shellcheck in pre-commit environment

### ISSUE THREAD

**Issue by louwers** [rhysd/actionlint#324]
The environment that `pre-commit` is set up with does not include `shellcheck`.

I tried this

```
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.25
  hooks:
    - id: actionlint
      additional_dependencies:
        - "shellcheck-py"
```

But then it looks for a Go shellcheck package...
