### ISSUE TITLE
Check if webhook event exists before parsing is as such

### ISSUE THREAD

**Issue by TheFox0x7** [rhysd/actionlint#348]
Currently if the event doesn't match any predefined one actionlint creates a webhook event in this case for `Workflow_Dispatch`.
```yaml

on:
  Workflow_Dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    
    steps:
      - run: "foobar"
```
