### ISSUE TITLE
Exclude ${{ insert }} from expression linter

### ISSUE THREAD

**Issue by TheFox0x7** [rhysd/actionlint#349]
```yaml
on: push
jobs:
  _:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        include:
        - os: ubuntu-latest # Only ubuntu-latest has an extra env var MYVAR
          env:
            MYVAR: myval
            MYVAR2: myval2
    env:
      SOME_ENV: B
      ${{ insert }}: ${{ matrix.env || fromjson('{}') }}
    runs-on: ${{ matrix.os }}
    steps:
    - run: env
```

This workflow currently returns error
`job.yaml:16:11: undefined variable "insert". available variables are "env", "github", "inputs", "job", "matrix", "needs", "runner", "secrets", "steps", "strategy", "vars" [expression]`

`${{ insert }}` is an undocumented expression which:
> inserts a mapping into a mapping from an expression result.

Related discussion about the expression: https://github.com/go-gitea/gitea/issues/24603#issuecomment-1704043290
