### ISSUE TITLE
Warning if explicit shell is not set

### ISSUE THREAD

**Issue by jayvdb** [rhysd/actionlint#374]
I've encountered that github actions uses `sh` as the `shell` even when `bash` is on the worker image, unless `shell: bash` is explicitly added, either for the step or using the `defaults` https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#example-set-the-default-shell-and-working-directory

IMO it would be useful for actionlint to check whether there is an explicit `shell` set for any step which uses `run`, so that the language for the script is known.

**Comment by michaelvoet** [comment]
Here's evidence of this issue:

```yaml
- name: Print default shell
   run: |
       ps -p $$
- name: Print bash shell
   shell: bash
   run: |
       ps -p $$
```

![image](https://github.com/rhysd/actionlint/assets/101036482/90e8445c-0120-478a-9d40-e86d24dc8656)
