### ISSUE TITLE
Support glob/regex patterns for self hosted runner labels configuration

### ISSUE THREAD

**Issue by kishaningithub** [rhysd/actionlint#377]
## Context
To add self hosted runners to the list i am doing something like

```yaml
self-hosted-runner:
    labels:
      - private-runner-label1
      - private-runner-label2
```

but the problem the above way of configuration is not ideal if the label contains a dynamic elements, For example 

```yaml
self-hosted-runner:
    labels:
      - INSTANCE_TYPE=m6a.large # Yes this is a label :-)  
```

In the above the value of the INSTANCE_TYPE can be anything (t3.large, m2.large etc etc) and they are all valid github runner labels

## Proposal

It would be great if this configuration can be made into a pattern like

```yaml
self-hosted-runner:
    labels:
      - INSTANCE_TYPE=*  # The * matches everything  
```

This way i don't have to specify each and every label
