### ISSUE TITLE
feature request: detect invalid reference to a workflow file

### ISSUE THREAD

**Issue by jerguslejko** [rhysd/actionlint#391]
I would like to get a lint failure, when I use incorrect reference to a workflow file in the repo.

example:

```yaml
  # ...

   - name: Deploy
     uses: ./.github/actions/whoops-I-put-wrong-path-here
     with:
       arg1: value1
```
