### ISSUE TITLE
Disallow usage of `>-`, which is not supported by GitHub actions

### ISSUE THREAD

**Issue by sarayourfriend** [rhysd/actionlint#397]
GitHub actions subset of YAML does not support `>-`: https://github.com/actions/runner/issues/418#issuecomment-612928525

A lint error should be raised when `>-` is used to prevent the headache of finding out it doesn't work.

**Comment by rhysd** [comment]
I didn't know this behavior. It looks nice if actionlint can catch it. I need to check how go-yaml parses the syntax. Can you provide some sample YAML input which should cause the error?

**Comment by rhysd** [comment]
I tried this on my test repository but it looks that `>-` is supported.

Workflow was:

```yaml
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: >-
          echo foo
          bar
```

And `echo foo bar` seemed to be executed correctly.

![image](https://github.com/rhysd/actionlint/assets/823277/9ddda75d-7005-4144-ab66-207828feca57)

Am I misunderstanding anything?
