### ISSUE TITLE
Failed on "google-github-actions/get-secretmanager-secrets"

### ISSUE THREAD

**Issue by dragon3** [rhysd/actionlint#404]
Since the version `1.6.27`, the `actionlint` failed on the following correct workflow configuration:

```yaml
name: test

on:
  push

jobs:
  job_id:
    runs-on: ubuntu-latest

    steps:
    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v2'
      with:
        secrets: |-
          token:my-project/docker-registry-token

    # other step
    - id: 'publish'
      uses: 'foo/bar@v1'
      env:
        TOKEN: '${{ steps.secrets.outputs.token }}'
```
📓  This workflow configuration is an example based on https://github.com/google-github-actions/get-secretmanager-secrets?tab=readme-ov-file#outputs

```
➜  actionlint test.yml
test.yml:21:21: property "token" is not defined in object type {} [expression]
   |
21 |         TOKEN: '${{ steps.secrets.outputs.token }}'
   |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
➜  actionlint --version
1.6.27
installed by building from source
built with go1.22.0 compiler for darwin/arm64
```

I confirmed that `1.6.26` works without error as expected.

**Comment by rhysd** [comment]
This is because the action does not define the output in the manifest. I'll make a pull request there.

https://github.com/google-github-actions/get-secretmanager-secrets/blob/main/action.yml

**Comment by rhysd** [comment]
Created: https://github.com/google-github-actions/get-secretmanager-secrets/pull/283

**Comment by dragon3** [comment]
@rhysd 
Thank you for the comment and for creating the pull request.

However, the `google-github-actions/get-secretmanager-secrets` creates the outputs dynamically from the `secrets` attribute.

For example, the following configuration creates `foo1` and `bar2` outputs dynamically.
```
    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v2'
      with:
        secrets: |-
          foo1:xxx
          bar2:xxx

# The dynamic outputs can be used in other steps
# ${{ steps.secrets.outputs.foo1 }}
# ${{ steps.secrets.outputs.bar2 }}
```

Do you have any idea to support that on `actionlint`?
