### ISSUE TITLE
v1.6.27 Actionlint do not recognising outputs from google-github-actions/get-secretmanager-secrets@v2

### ISSUE THREAD

**Issue by tb137** [rhysd/actionlint#405]
After upgrading from v1.6.24 to v1.6.27 actionlint do not recognising outputs from google-github-actions/get-secretmanager-secrets@v2. It complains with following error:
```
.github/workflows/dotnet-basic.yml:251:34: property "service_account_key" is not defined in object type {} [expression]
    |
251 |           credentials_json: '${{ steps.get-secrets.outputs.service_account_key }}'
```
It used to work before just fine, but after an upgrade it started to complain :/ 

GitHub action workflow looks like that:
```
...
       - id: get-secrets
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            service_account_key:gcp-project/secret_account_key
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          credentials_json: '${{ steps.get-secrets.outputs.service_account_key }}
...
```

Would you know how to resolve this issue? Is it a bug? 

Thank you!

P.S. It brakes only in 1.6.27.
