### ISSUE TITLE
Seems like actionlint lack support when we call reusable workflow in the main workflow.

### ISSUE THREAD

**Issue by IAMDAVID0921** [rhysd/actionlint#407]
In Main workflow:
we call reusable workflow like:
```
 Build-abc:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      xxxx: xxxxx
      yyyy: yyyyy
```
Then we want to use the abc_output from the reusable workflow as an input in another reusable workflow, we do something like:
```
Run-abc-test:
    uses: ./.github/workflows/another_reusable_workflow.yml
    with:
      abc_value: ${{ needs.Build-abc.outputs.abc_version }}
```
This will make actionlint fail as
```
.github/workflows/another_reusable_workflow.yml:64:31: property "build-abc" is not defined in object type {promote-bundle: {outputs: {}; result: string}} [expression]
   |
64 |                 abc_value: ${{ needs.Build-abc.outputs.abc_version }}
   |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: Process completed with exit code 1.
```

Reusable workflow:
```
name: Build abc
on:
  workflow_call:
    inputs:
      xxxx:
        required: true
        type: string
      yyyy:
        required: true
        type: string
    outputs:
      abc_version:
        value: ${{ xxxx.xxxx.xxxx }}
```

**Comment by rhysd** [comment]
I can't fully understand your issue only from the code snippets, but I could not reproduce this from the following workflows.

main.yml

```yaml
on: push

jobs:
  Build-abc:
    uses: ./reusable_workflow.yml
  run-abc-test:
    needs: [Build-abc]
    uses: ./another_reusable_workflow.yml
    with:
      abc_value: ${{ needs.Build-abc.outputs.abc_version }}
```

reusable_workflow.yml

```yaml
on:
  workflow_call:
    outputs:
      abc_version:
        description: "..."
        value: "..."
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - run: echo reusable
```

another_reusable_workflow.yml

```yaml
on:
  workflow_call:
    inputs:
      abc_value:
        description: "..."
        type: string
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - run: echo another reusable
```

actionlint reported no error.

**Comment by rhysd** [comment]
Please tell me entire workflows which can **reproduce** your issue.

**Comment by ssbarnea** [comment]
That is a real issue, here a another example:
```
.github/workflows/tox.yml:237:21: property "passed_name" is not defined in object type {} [expression]
    |
237 |           name: ${{ matrix.passed_name }}
    |                     ^~~~~~~~~~~~~~~~~~
```

As you can see, the matrix values is loaded from output of another job, so I am not surprised that the linter is not able to find it. For cases like this we need a way to disable the rule, as static checking cannot detect these:

```yaml
  build:
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
```

**Comment by rhysd** [comment]
Again, please tell me **entire** workflows which can **reproduce** your issue.

**Comment by syhe** [comment]
I believe most of these issues stem from overlooking that you have to declare `outputs` _twice_ when writing a reusable workflow, since the `workflow_call` trigger wants a mapping of the _job_ outputs to the _workflow_ outputs.

See [the relevant section of the documentation](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#using-outputs-from-a-reusable-workflow).

Perhaps the error message could be improved for this case?

**Comment by hasansezertasan** [comment]
I am having a similar problem @rhysd. Here is my workflow to reproduce my issue:

---

I am using uv and followed their documentation for using uv in my CI.

Here is my sample GHA:

```yml
---
name: Build
on:
  workflow_dispatch:
  push:
    branches: ["main"]  # Disable when using release.yml
  pull_request:
    branches: ["main"]
jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.12"
          enable-cache: true
      - name: Restore cache
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"
      - name: Install dependencies
        run: uv sync
      - name: Build the Wheel
        run: uv build --wheel
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: ./dist/*.whl
          if-no-files-found: error

```

When I run `actionlint .github/workflows/sample.yml` command, the output:

```bash

.github/workflows/sample.yml:36:13: property "setup-uv" is not defined in object type {} [expression]
   |
36 |         if: steps.setup-uv.outputs.cache-hit == 'true'
   |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

[uv action docs](https://github.com/astral-sh/setup-uv/blob/main/README.md?plain=1#L185-L192)
