### ISSUE TITLE
Default shell not being detected - currently treats all `run` on Linux as shell

### ISSUE THREAD

**Issue by ElvenSpellmaker** [rhysd/actionlint#409]
When using a default shell:
```yaml
defaults:
  run:
    shell: pwsh
```

It's not being detected and actionlint is calling `shellcheck` on all runs without an explicit shell.

Ideally this would be taken into account and all run would use the default shell defined.

We use `pwsh` on Linux (as pwsh is cross-OS and a better scripting language than bash) so #315 isn't a solution of just branching workflows.

Relevant Issues: https://github.com/rhysd/actionlint/issues/315

**Comment by rhysd** [comment]
Would you share a minimal complete workflow which actionlint can cause the issue?

**Comment by rhysd** [comment]
I confirmed that this is a bug when actionlint fails to detect Windows runner from `runs-on`.

Reproduction:

```yaml
on: push

defaults:
  run:
    shell: pwsh

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          $Env:FOO = "FOO"
```

This doesn't reproduce when a Windows runner is directly set:

```yaml
on: push

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: |
          $Env:FOO = "FOO"
```
