### ISSUE TITLE
Naming convention for inputs

### ISSUE THREAD

**Issue by nitrocode** [rhysd/actionlint#450]
## what

It would be nice to have consistent action inputs

Perhaps the default opinion can be kebab case and be configurable

## why

Consistency

## info

---

kebab case for all inputs

```yaml
inputs:
  my-input-to-action:
    description: 'some description'
    required: false
```

vs snake case for all inputs

```yaml
inputs:
  my_input_to_action:
    description: 'some description'
    required: false
```

vs mixed

```yaml
inputs:
  my-input_to_action:
    description: 'some description'
    required: false
```

## references

- https://github.com/orgs/community/discussions/39547
