### ISSUE TITLE
Provide more complete / more examples of configuration

### ISSUE THREAD

**Issue by coilysiren** [rhysd/actionlint#471]
I don't totally understand how to turn https://github.com/rhysd/actionlint/blob/v1.7.4/docs/config.md into the configuration I need. Also it looks like there's a typo in the example, near `.github/workflows/**/*.yaml`.

I am trying to configure that application with the following configuration:

```yaml
paths:
  # actionlint doesn't know how to handle the json inside of this file
  ci-cron-vulnerability-scans.yml:
    ignore:
      - Quote this to prevent word splitting
```

And unfortunately it's not working. It's still giving me

> .github/workflows/ci-cron-vulnerability-scans.yml:29:9: shellcheck reported issue in this script: SC2046:warning:18:12: Quote this to prevent word splitting [shellcheck]

Shown here: https://github.com/HHS/simpler-grants-gov/actions/runs/11746633221/job/32726817220?pr=2785
