### ISSUE TITLE
Available contexts check wrongly checking `input` usage in `with` context.

### ISSUE THREAD

**Issue by maikelvdh** [rhysd/actionlint#495]
The following construct is flagged as invalid (`context "inputs" is not allowed here. no context is available here.`):
```
uses: docker://<image-name>:latest
with:
  entrypoint: /bin/sh
  args: >
    --arg "${{ inputs.arg }}"
```

Though based on https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#context-availability this is valid, and equally this works fine.
