### ISSUE TITLE
Prevent attempts to use local actions in jobs before a repo is checked out

### ISSUE THREAD

**Issue by roryabraham** [rhysd/actionlint#514]
A mistake I have made a few times is to try using a local action before checking out the repo

```yml
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/composite/myAction
```

This will fail unless you add an `actions/checkout` first. It would be great if this tool could catch such a case.
