### ISSUE TITLE
Globs starting with `./` never match

### ISSUE THREAD

**Issue by 9999years** [rhysd/actionlint#521]
This job will never run, because globs starting with `./` are never matched:

```yaml
on:
  pull_request:
    paths:
      - './src/**'
```

This behavior is surprising and easy to check. Let's add a check for it.
