### ISSUE TITLE
input "artifact-ids" is not defined in action "actions/download-artifact@v4"

### ISSUE THREAD

**Issue by waqaskayani** [rhysd/actionlint#537]
The `actions/download-artifact@v4` action has an input field `artifact-ids` as per [documentation](https://github.com/actions/download-artifact?tab=readme-ov-file#inputs), that allows to download artifacts based on their IDs. The linter does not recognizes it and throws this error.
```
input "artifact-ids" is not defined in action "actions/download-artifact@v4". available inputs are "github-token", "merge-multiple", "name", "path", "pattern", "repository", "run-id" [action]
```

This needs to be added to allow:
```yaml
      - uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ inputs.artifact-ids }}
```
