### ISSUE TITLE
Publishing actions in github marketplace

### ISSUE THREAD

**Issue by kyo-ago** [rhysd/actionlint#54]
Please [publishing actions in GitHub Marketplace](https://docs.github.com/actions/creating-actions/publishing-actions-in-github-marketplace).

[I know there is documentation](https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions), but I would like the official action to be published for the following reasons:

* Fixing the version, can safely a major version up.
* Avoiding the use of bash improves the readability of the user's action.

**Comment by rhysd** [comment]
I'm sorry for the late response because I was focusing on other project. Now I'm back.

Let me ask a question. What is the problem you want to solve? We offer a download script which installs actionlint with one command. Checking workflow files on GitHub Actions can be done with only one step. So I'm not feeling that a dedicated action is necessary.

```yaml
- name: Check workflow files
  run: |
    bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
    ./actionlint -color
  shell: bash
```
