### ISSUE TITLE
Support using the container in a workflow

### ISSUE THREAD

**Issue by toast-gear** [rhysd/actionlint#65]
I wish to use this great tool's docker container in a workflow as this greatly simplifies the pipeline.

Pre-commit hooks are great but some developers turn them off when they just want to get something finished and so it can be nicer to have actionlint in a workflow instead sometimes. Additionally, as this tool is somewhat niche, some developers may not know much about it so putting it in a pipeline can help with that too. The container doesn't seem to have an accessible shell in it and so I can't override the entrypoint to something that will enable me to define some steps in a workflow before running the `actionlint` command.

An example below of what I was thinking:

```
name: Lint Workflows

on:
  pull_request:
    type:
      - synchronize
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    container: 
      image: rhysd/actionlint:latest
      args: sh
    steps:
      - name: Run lint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          actionlint -color
```

**Comment by crqra** [comment]
Wouldn't something like this be useful for you?

```yaml
name: Lint Workflows

on:
  pull_request:
    type:
      - synchronize
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          brew install actionlint
          actionlint -color
```
