### ISSUE TITLE
Feature request: event name in expressions can result in expression always evaluating to false

### ISSUE THREAD

**Issue by webignition** [rhysd/actionlint#68]
An incorrect event name reference in an expression can result in the expression always evaluating to `false`.

An expression that always evaluates to false suggests either:
 - the expression is mistakenly incorrect and needs fixing
 - a job or step whose execution is controlled by an expression needs to be removed

Take the following simplified workflow as an example:

 ```yaml
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Do something with the checked-out code
          git status
```

The example workflow will always fail. The expression controlling execution of the `Checkout code` step will always evaluate to `false`. In this case, either the expression needs changing to `github.event_name == 'push'` or the expression-controlled step needs to be removed.

Whilst it is probably impossible to determine whether any arbitrary expression always evaluates to false (sounds like a halting problem situation), it is probably possible to determine whether an expression containing an event name reference always evaluates to false as the event names to which a workflow responds are always present.
