### ISSUE TITLE
The env reference cannot happen on the same level

### ISSUE THREAD

**Issue by chenrui333** [rhysd/actionlint#74]
The env variable cannot reference another env variable at the same level, for example, it wont work like this

```
env:
  IS_QA: "qa"
  PROJECT: "important"
  LOCAL_TAG: "${{env.IS_QA}}-latest"
  AWS_TASKDEF: "project-${{env.PROJECT}}-something"
```

But it can be put into different levels as below would work

```
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      IS_QA: "qa"
      PROJECT: "important"
    steps:
      - run:
          echo ${{env.IS_QA}}
          echo ${{env.LOCAL_TAG}}
          echo ${{env.PROJECT}}
          echo ${{env.AWS_TASKDEF}}
        env:
          LOCAL_TAG: "${{env.IS_QA}}-latest"
          AWS_TASKDEF: "project-${{env.PROJECT}}-something"
```

so ref, https://stackoverflow.com/questions/69979085/github-actions-using-variables-in-global-env-section
