### ISSUE TITLE
`input "node-version-file" is not defined` error in `actions/setup-node`

### ISSUE THREAD

**Issue by ybiquitous** [rhysd/actionlint#86]
Hi, thanks a lot for creating the nice tool!

[`actions/setup-node@v2.5.0`](https://github.com/actions/setup-node/releases/tag/v2.5.0) has newly supported the `node-version-file` parameter, so it would be so happy if actionlint could support also the parameter!

Current:

`.github/workflows/ci.yml`:

```yaml
name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
```

```console
$ actionlint .github/workflows/ci.yml
.github/workflows/ci.yml:9:11: input "node-version-file" is not defined in action "actions/setup-node@v2". available inputs are "always-auth", "architecture", "cache", "cache-dependency-path", "check-latest", "node-version", "registry-url", "scope", "token", "version" [action]
   |
11 |           node-version-file: .nvmrc
   |           ^~~~~~~~~~~~~~~~~~
```

Version:

```console
$ actionlint -version
1.6.8
installed by building from source
built with go1.17.2 compiler for darwin/arm64
```
