### ISSUE TITLE
Adding workflow_call to a workflow fails lint

### ISSUE THREAD

**Issue by BretFisher** [rhysd/actionlint#87]
If I add `workflow_call` to a simple workflow, I'll get an error about an env later in the file.

### This passes actionlint 1.6.8:

```yaml
---
name: Lint Code Base

on:
  push:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### This fails (only added one line `workflow_call`)

```yaml
---
name: Lint Code Base

on:
  push:
  workflow_call:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### error:

```text
 property "github_token" is not defined in object type {} [expression]
   |
24 |           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   |                             ^~~~~~~~~~~~~~~~~~~~
```
