### ISSUE TITLE
unexpected key "outputs" for "workflow_call" section. expected one of "inputs", "secrets"

### ISSUE THREAD

**Issue by faultymonk** [rhysd/actionlint#91]
Howdy, came across this error while using `outputs` in a reusable workflow:

```
unexpected key "outputs" for "workflow_call" section. expected one of "inputs", "secrets" [syntax-check]
```

The workflow works properly, and is in keeping with the github actions workflow [syntax example](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-1).

```
on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.my_job.outputs.job_output1 }}
      workflow_output2:
        description: "The second job output"
        value: ${{ jobs.my_job.outputs.job_output2 }}  
```
