### ISSUE TITLE
input "cache" is not defined in action "actions/setup-python@v2". available inputs are "architecture", "python-version", "token"

### ISSUE THREAD

**Issue by toast-gear** [rhysd/actionlint#95]
**Error** 
```
input "cache" is not defined in action "actions/setup-python@v2". available inputs
are "architecture", "python-version", "token"
```

**Steps to Reproduce**

1. Create this workflow:

```yaml
name: My Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          cache: 'pip'
```

2. Lint this workflow with actionlint

**Links**
https://github.com/actions/setup-python#caching-packages-dependencies caching is a somewhat new input for this action
https://github.com/actions/setup-python/blob/main/action.yml there are a few additional inputs compared to the current whitelist
